# The single source of truth for all services and resources in the system.
# This version uses snake_case to match the Go struct tags in types.go.

default_project_id: "gemini-power-test"
default_location: "EU" # For multi-region resources like GCS/BigQuery
default_region: "europe-west1" # Specific region for Cloud Run services

environments:
  test:
    project_id: "gemini-power-test"
    default_region: "europe-west1" # Can override the top-level default
  production:
    project_id: "your-prod-gcp-project-id" # CHANGE THIS
    default_region: "us-central1"

services:
  - name: "ingestion-service"
    description: "Receives data from MQTT and publishes to Pub/Sub."
    service_account: "ingestion-sa@your-gcp-project.iam.gserviceaccount.com"
    source_path: "ingestion" # Path from project root
    min_instances: 1 # <-- Keep 1 instance warm
    health_check:
      port: 8080
      path: "/healthz"
    metadata:
      # Service-specific configuration that will become environment variables
      broker_url: "tcp://broker.emqx.io:1883"
      topic: "garden_monitor/861275073104248"
      client_id_prefix: "garden_broker"

  - name: "analysis-service"
    description: "Consumes from Pub/Sub and inserts into BigQuery."
    service_account: "analysis-sa@your-gcp-project.iam.gserviceaccount.com"
    source_path: "bigquery" # Path from project root
    min_instances: 1 # <-- Keep 1 instance warm
    health_check:
      port: 8080
      path: "/healthz"

dataflows:
  - name: "test-mqtt-to-bigquery"
    description: "Dataflow for the test environment."
    services:
      - "ingestion-service"
      - "analysis-service"
    lifecycle:
      strategy: "permanent"

  - name: "prod-mqtt-to-bigquery"
    description: "The main production dataflow pipeline."
    services:
      - "ingestion-service"
      - "analysis-service"

resources:
  # --- Test Resources ---
  pubsub_topics:
    - name: "test-device-data"
      producer_service: "ingestion-service"
  pubsub_subscriptions:
    - name: "test-analysis-service-sub"
      topic: "test-device-data"
      consumer_service: "analysis-service"
  bigquery_datasets:
    - name: "test_device_analytics"
      description: "Dataset for storing test telemetry."
  bigquery_tables:
    - name: "test_monitor_payloads"
      dataset: "test_device_analytics"
      accessing_services: ["analysis-service"]
      schema_source_type: "go_struct"
      schema_source_identifier: "github.com/illmade-knight/ai-power-mpv/pkg/types.GardenMonitorPayload"

  # gcs_buckets: [] # GCS section is optional

